#!/usr/bin/env python3
"""Build a local sales-popularity signal for the Flora catalog.

Parses the store's own 2025 sales reports (units sold per product code, from
Jan-Nov) and joins them to the imported catalog by exact stock code. This
powers a deterministic "mais procurado" signal used only as a local
tie-breaker in the recommendation engine -- no network or cloud service is
involved, and no data outside the store's own reports is used.

Only Ervas e Temperos and Fertilizantes have a real sales report in
base_de_dados. No sales report was provided for Flores e Plantas, so that
category is intentionally left out of the popularity signal rather than
guessed.
"""

from __future__ import annotations

import csv
import json
import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
BASE_DIR = PROJECT_ROOT.parent / "base_de_dados" / "utf8"
CATALOG_PATH = PROJECT_ROOT / "src" / "data" / "products.generated.ts"
OUTPUT_PATH = PROJECT_ROOT / "src" / "data" / "sales-popularity.generated.ts"

SALES_FILES = [
    BASE_DIR / "22 - Ervas e Temperos - 2025 - Sheet1.csv",
    BASE_DIR / "FERTILIZANTES Relação mais vendidos Janeiro_Novembro 2025 (1).xlsx - Sheet1.csv",
]

CODE_COLUMN = 0
QUANTITY_COLUMN = 8
CODE_PATTERN = re.compile(r"^\d{8}$")
TOP_SELLER_COUNT = 40


def parse_quantity(raw: str) -> float | None:
    raw = raw.strip().strip('"')
    if not raw:
        return None
    normalized = raw.replace(".", "").replace(",", ".")
    try:
        return float(normalized)
    except ValueError:
        return None


def load_known_codes() -> set[str]:
    text = CATALOG_PATH.read_text(encoding="utf-8")
    return set(re.findall(r'"code": "(\d{8})"', text))


def load_sales_totals() -> dict[str, float]:
    totals: dict[str, float] = {}
    for path in SALES_FILES:
        if not path.exists():
            raise FileNotFoundError(f"Missing sales report: {path}")
        with path.open(encoding="utf-8-sig", newline="") as handle:
            for row in csv.reader(handle):
                if len(row) <= QUANTITY_COLUMN:
                    continue
                code = row[CODE_COLUMN].strip()
                if not CODE_PATTERN.match(code):
                    continue
                quantity = parse_quantity(row[QUANTITY_COLUMN])
                if quantity is None:
                    continue
                totals[code] = totals.get(code, 0.0) + quantity
    return totals


def main() -> None:
    known_codes = load_known_codes()
    sales_totals = load_sales_totals()
    matched = {code: quantity for code, quantity in sales_totals.items() if code in known_codes}
    ranked = sorted(matched.items(), key=lambda item: item[1], reverse=True)

    lines = [
        "// Generated by scripts/prepare-sales-popularity.py. Do not edit manually.",
        "// Units sold Jan-Nov 2025, from the store's own sales reports (Ervas e Temperos",
        "// and Fertilizantes only; no sales report was provided for Flores e Plantas).",
        "export const salesUnitsByProductCode: Record<string, number> = {",
    ]
    for code, quantity in ranked:
        lines.append(f'  "{code}": {int(round(quantity))},')
    lines.append("}")
    lines.append("")
    top_sellers = json.dumps([code for code, _ in ranked[:TOP_SELLER_COUNT]])
    lines.append(f"export const topSellingProductCodes: string[] = {top_sellers}")
    lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Matched {len(matched)} of {len(sales_totals)} sales rows to catalog codes.")
    print(f"Wrote {OUTPUT_PATH.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
